namespace Imp.Base.Subtitles
{
    public enum StyleDefinitions
    {
        Name,
        Fontname,
        Fontsize,
        PrimaryColour,
        SecondaryColour,
        OutlineColour,
        BackColour,
        Bold,
        Italic,
        Underline,
        StrikeOut,
        ScaleX,
        ScaleY,
        Spacing,
        Angle,
        BorderStyle,
        Outline,
        Shadow,
        Alignment,
        MarginL,
        MarginR,
        MarginV,
        Encoding
    }
}
